version: '3.9'

services:
  carapp-api:
    build:
      context: .
      dockerfile: CarApp.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=carapp.db
      - Redis__Configuration=redis:6379
    depends_on:
      - redis
    volumes:
      # Bind mount host logs folder to container logs folder
      - C:/CarApp/Logs:/app/Logs   # maps host logs to container logs folder

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
